DATASET_FOLDER = "./test/data"
PRETRAIN_MODEL = "hoang14/viettel-phobert-finetune-viquad"
EPOCHS = 15
LR = 2e-5
BATCH_SIZE = 2
MAX_ANSWER_LENGTH = 200
MAX_LENGTH = 258  # Goc 356
STRIDE = 100
N_BEST = 20
DEVICE = "cuda"